[package]
name = "sdml-core"
description = "Core Model for Simple Domain Modeling Language (SDML)"
version = "0.1.9"
authors = ["Simon Johnston <johnstonskj@gmail.com>"]
repository = "https://github.com/johnstonskj/rust-sdml.git"
license = "MIT"
readme = "README.md"
edition = "2021"
publish = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
all-features = true
rustdoc-args = [ "--html-in-header", "doc-src/header.html" ]

[features]
serde = ["dep:serde"]

[dependencies]
codespan-reporting = "0.11.1"
indent_write = "2.2.0"
lazy_static = "1.4.0"
ordered-float = { version = "3.7.0", features = [ "serde" ] }
paste = "1.0.12"
regex = "1.8.4"
rust_decimal = { version = "1.30.0", features = [ "serde" ] }
serde = { version = "1.0.171", features = [ "derive" ], optional = true }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = [ "env-filter" ] }
tree-sitter = "0.20.10"
url = { version = "2.4.0", features = [ "serde" ] }

[dev-dependencies]
pretty_assertions = "1.3.0"
