[package]
name = "sdml-parse"
description = "Parser for Simple Domain Modeling Language (SDML)"
version = "0.2.2"
authors = ["Simon Johnston <johnstonskj@gmail.com>"]
repository = "https://github.com/johnstonskj/rust-sdml.git"
license-file = "../LICENSE"
readme = "README.md"
edition = "2021"
publish = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
all-features = true

[dependencies]
sdml-core = { version = "0.2.1", features = ["serde"], path = "../sdml-core" }
codespan-reporting = "0.11.1"
lazy_static = "1.4.0"
ordered-float = "4.1.1"
regex = "1.10.2"
rust_decimal = "1.30.0"
search_path = "0.1.4"
serde = { version = "1.0.190", features = ["derive"] }
serde_json = "1.0.108"
tracing = "0.1.40"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
tree-sitter = "0.20.10"
tree-sitter-sdml = "0.2.12"
url = { version = "2.4.0", features = ["serde"] }

[dev-dependencies]
paste = "1.0.14"
pretty_assertions = "1.4.0"
