[package]
name = "sdml-parse"
description = "Parser for Simple Domain Modeling Language (SDML)"
version = "0.1.6"
authors = ["Simon Johnston <johnstonskj@gmail.com>"]
repository = "https://github.com/johnstonskj/rust-sdml.git"
license = "MIT"
readme = "README.md"
edition = "2021"
publish = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
all-features = true

[dependencies]
sdml-core = { version = "0.1", features = [ "serde" ], path = "../sdml-core" }
codespan-reporting = "0.11.1"
lazy_static = "1.4.0"
ordered-float = "3.7.0"
paste = "1.0.13"
regex = "1.9.1"
rust_decimal = "1.30.0"
search_path = "0.1.4"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = [ "env-filter" ] }
tree-sitter = "0.20.10"
tree-sitter-sdml = { version = "0.1.26", path = "../../../tree-sitter-sdml" }
url = { version = "2.4.0", features = [ "serde" ] }
serde = { version = "1.0.171", features = [ "derive" ] }
serde_json = "1.0.102"
syn = "^2.0.25" # Version conflict

[dev-dependencies]
pretty_assertions = "1.4.0"
