[package]
name = "sdml-parse"
description = "Parser for Simple Domain Modeling Language (SDML)"
version = "0.2.8"
authors = ["Simon Johnston <johnstonskj@gmail.com>"]
repository = "https://github.com/johnstonskj/rust-sdml.git"
license-file = "../LICENSE"
readme = "README.md"
edition = "2021"
publish = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
all-features = true

[dependencies]
codespan-reporting = "0.11.1"
rust_decimal = "1.30.1"
sdml-core = { version = "0.2.10", features = ["serde"], path = "../sdml-core" }
sdml_error = { version = "0.1.0", path = "../sdml_error" }
search_path = "0.1.4"
serde = { version = "1.0.195", features = ["derive"] }
serde_json = "1.0.111"
tracing = "0.1.40"
tree-sitter = "0.20.10"
tree-sitter-sdml = "0.2.16"
url = { version = "2.5.0", features = ["serde"] }

[dev-dependencies]
paste = "1.0.14"
pretty_assertions = "1.4.0"
