[package]
name = "sdml-cli"
description = "Rust CLI for Simple Domain Modeling Language (SDML)"
version = "0.2.3"
authors = ["Simon Johnston <johnstonskj@gmail.com>"]
repository = "https://github.com/johnstonskj/rust-sdml.git"
license-file = "../LICENSE"
readme = "README.md"
edition = "2021"
publish = true

[[bin]]
name = "sdml"
path = "src/main.rs"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
all-features = true

[dependencies]
ansi_term = "0.12.1"
clap = { version = "4.4.18", features = ["derive", "env", "wrap_help"] }
clap-verbosity-flag = "2.1.2"
codespan-reporting = "0.11.1"
lazy_static = "1.4.0"
ordered-float = "4.2.0"
regex = "1.10.2"
rust_decimal = "1.33.1"
sdml-core = { version = "0.2.4", path = "../sdml-core" }
sdml-parse = { version = "0.2.3", path = "../sdml-parse" }
sdml-generate = { version = "0.2.4", path = "../sdml-generate" }
search_path = "0.1.4"
tempfile = "3.9.0"
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
tree-sitter = "0.20.10"
tree-sitter-highlight = "0.20.1"
tree-sitter-sdml = "0.2.12"
url = "2.5.0"

[dev-dependencies]
pretty_assertions = "1.3.0"
