[package]
name = "sdml-cli"
description = "Rust CLI for Simple Domain Modeling Language (SDML)"
version = "0.2.5"
authors = ["Simon Johnston <johnstonskj@gmail.com>"]
repository = "https://github.com/johnstonskj/rust-sdml.git"
license-file = "../LICENSE"
readme = "README.md"
edition = "2021"
publish = true

[[bin]]
name = "sdml"
path = "src/main.rs"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
all-features = true

[dependencies]
clap = { version = "4.4.18", features = ["derive", "env", "wrap_help"] }
clap-verbosity-flag = "2.1.2"
sdml-core = { version = "0.2.8", path = "../sdml-core" }
sdml-parse = { version = "0.2.6", path = "../sdml-parse" }
sdml-generate = { version = "0.2.6", path = "../sdml-generate" }
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
tree-sitter-sdml = "0.2.12"
