[package]
name = "sdml-generate"
description = "Simple Domain Modeling Language (SDML) generated Artifacts"
version = "0.2.11"
authors = ["Simon Johnston <johnstonskj@gmail.com>"]
repository = "https://github.com/johnstonskj/rust-sdml.git"
license-file = "../LICENSE"
readme = "README.org"
edition = "2021"
publish = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
all-features = true

[dependencies]
nu-ansi-term = "0.50.0"
regex = "1.10.3"
sdml-core = { version = "0.2.15", features = ["serde"], path = "../sdml-core" }
sdml_error = { version = "0.1.5", path = "../sdml_error" }
serde = { version = "1.0.195", features = ["derive"] }
serde_json = "1.0.113"
serde_regex = "1.1.0"
tempfile = "3.10.0"
text_trees = "0.1.2"
tracing = "0.1.40"
tree-sitter-highlight = "0.20.1"
tree-sitter-sdml = "0.2"
url = "2.5.0"

[dev-dependencies]
paste = "1.0.14"
pretty_assertions = "1.3.0"
sdml-parse = { version = "0.2.9", path = "../sdml-parse" }
