[package]
name = "sdml-generate"
description = "Simple Domain Modeling Language (SDML) generated Artifacts"
version = "0.2.4"
authors = ["Simon Johnston <johnstonskj@gmail.com>"]
repository = "https://github.com/johnstonskj/rust-sdml.git"
license-file = "../LICENSE"
readme = "README.md"
edition = "2021"
publish = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
all-features = true

[dependencies]
sdml-core = { version = "0.2.4", path = "../sdml-core" }
ansi_term = "0.12.1"
codespan-reporting = "0.11.1"
lazy_static = "1.4.0"
ordered-float = "4.2.0"
regex = "1.10.2"
rust_decimal = "1.32.0"
tempfile = "3.9.0"
text_trees = "0.1.2"
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
tree-sitter = "0.20.10"
tree-sitter-highlight = "0.20.1"
tree-sitter-sdml = "0.2"
url = "2.5.0"

[dev-dependencies]
pretty_assertions = "1.3.0"
